-- Short opaque token for share URLs so the URL form is just /s/<token>
-- with no bucket name, key, method, or expiry leaking through the path /
-- query string. The DB row remains the authoritative source of truth for
-- expiry, revocation, and what file the token unlocks.
--
-- Token format: 32 url-safe characters generated by crypto/rand on the
-- server. Indexed unique. The legacy /share/<bucket>/<key>?sig=... URLs
-- keep working for backward compatibility, but new presign responses now
-- hand out the /s/<token> form.

ALTER TABLE share_links
  ADD COLUMN IF NOT EXISTS url_token TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_share_links_url_token
  ON share_links(url_token) WHERE url_token IS NOT NULL;
