#!/usr/bin/env bash
# =============================================================================
# Generates a fresh .env with strong random secrets.
# Run this on a new server before `docker compose up -d`.
#
# Idempotent guard: refuses to overwrite an existing .env unless --force.
# =============================================================================

set -euo pipefail
cd "$(dirname "$0")/.."

if [ -f .env ] && [ "${1:-}" != "--force" ]; then
  echo "ERROR: .env already exists. Re-run with --force to overwrite."
  exit 1
fi

# Pick a random secret generator the system has
rand() {
  if command -v openssl >/dev/null; then
    openssl rand -base64 "${1:-24}" | tr -d '\n=+/' | cut -c1-"${1:-24}"
  else
    head -c "${1:-24}" /dev/urandom | base64 | tr -d '\n=+/' | cut -c1-"${1:-24}"
  fi
}

read -p "Admin email   [admin@local]: " ADMIN_EMAIL
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@local}"
read -s -p "Admin password (leave blank to generate): " ADMIN_PW; echo
if [ -z "$ADMIN_PW" ]; then
  ADMIN_PW=$(rand 16)
  echo "Generated admin password: $ADMIN_PW   (write this down NOW)"
fi

read -p "Storage directory on host [./storage]: " STORAGE_ROOT
STORAGE_ROOT="${STORAGE_ROOT:-./storage}"
mkdir -p "$STORAGE_ROOT"

read -p "Public URL or hostname (for tunnel) [http://localhost:8080]: " PUB_URL
PUB_URL="${PUB_URL:-http://localhost:8080}"

UID_LOCAL=$(id -u)
GID_LOCAL=$(id -g)

cat > .env <<EOF
# Generated by scripts/init-secrets.sh on $(date -u +%FT%TZ)
# DO NOT COMMIT THIS FILE.

# ---- PostgreSQL ----
POSTGRES_USER=s3admin
POSTGRES_PASSWORD=$(rand 32)
POSTGRES_DB=personals3
POSTGRES_PORT=5432

# ---- Initial admin user (only set on FIRST startup with a fresh DB) ----
ADMIN_EMAIL=$ADMIN_EMAIL
ADMIN_PASSWORD=$ADMIN_PW

# ---- Valkey ----
VALKEY_PORT=6379
VALKEY_PASSWORD=$(rand 32)

# ---- API ----
API_PORT=3000
API_HOST=0.0.0.0
UID=$UID_LOCAL
GID=$GID_LOCAL

DATABASE_URL=postgres://s3admin:\${POSTGRES_PASSWORD}@postgres:5432/personals3?sslmode=disable
VALKEY_URL=redis://:\${VALKEY_PASSWORD}@valkey:6379/0
JWT_SECRET=$(rand 64)

# ---- Dashboard ----
DASHBOARD_PORT=3001
NEXT_PUBLIC_API_URL=/api

# ---- Storage ----
STORAGE_ROOT=$STORAGE_ROOT
DEFAULT_QUOTA_BYTES=10737418240
MULTIPART_CHUNK_SIZE=5242880

# ---- Nginx ----
NGINX_HTTP_PORT=8080

# ---- Domains (informational) ----
API_DOMAIN=$PUB_URL
DASHBOARD_DOMAIN=$PUB_URL
SEGMENTS_DOMAIN=$PUB_URL

# ---- Worker ----
WORKER_POLL_INTERVAL=2
WORKER_CONCURRENCY=2

# ---- Cloudflare Tunnel (optional) ----
# Set this if using --profile tunnel; otherwise leave blank.
CLOUDFLARED_TOKEN=
EOF

chmod 600 .env

echo
echo "✓ .env written with fresh secrets."
echo "Next:"
echo "  docker compose up -d --build"
echo "Then open: $PUB_URL"
echo "Login:     $ADMIN_EMAIL"
echo "Password:  $ADMIN_PW"
echo
echo "Don't forget to back up .env — losing it locks you out of the DB."
